-- One-time Snowflake setup for PIPELINE_MODE=cloud.
-- Replace every <placeholder>; never commit real values.

CREATE DATABASE IF NOT EXISTS INVASIGHT;
CREATE SCHEMA IF NOT EXISTS INVASIGHT.RAW;
CREATE SCHEMA IF NOT EXISTS INVASIGHT.STAGING;
CREATE SCHEMA IF NOT EXISTS INVASIGHT.ANALYTICS;

CREATE WAREHOUSE IF NOT EXISTS INVASIGHT_WH
    WAREHOUSE_SIZE = XSMALL AUTO_SUSPEND = 60 AUTO_RESUME = TRUE;

-- RAW keeps data exactly as delivered: whole JSON payloads, ledger columns as text
CREATE TABLE IF NOT EXISTS INVASIGHT.RAW.FX_RATES_RAW (
    RAW VARIANT,
    FILE_NAME STRING,
    LOADED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);
CREATE TABLE IF NOT EXISTS INVASIGHT.RAW.METAL_PRICES_RAW LIKE INVASIGHT.RAW.FX_RATES_RAW;
CREATE TABLE IF NOT EXISTS INVASIGHT.RAW.EQUITY_PRICES_RAW LIKE INVASIGHT.RAW.FX_RATES_RAW;

CREATE TABLE IF NOT EXISTS INVASIGHT.RAW.LEDGER_TRANSACTIONS_RAW (
    TRANSACTION_ID STRING,
    CLIENT_ID STRING,
    CLIENT_NAME STRING,
    PORTFOLIO_ID STRING,
    TICKER STRING,
    TRANSACTION_TYPE STRING,
    QUANTITY STRING,
    PRICE STRING,
    CURRENCY STRING,
    FEE_AMOUNT STRING,
    TRANSACTION_DATE STRING,
    TRANSACTION_TS STRING,
    BATCH_ID STRING,
    FILE_NAME STRING,
    _LOADED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

-- External stage over the Blob container root, so COPY's FILES = (...) takes
-- the same relative paths the Airflow tasks land ("exchange_rates/2026-09-10.json")
CREATE STAGE IF NOT EXISTS INVASIGHT.RAW.LANDING_STAGE
    URL = 'azure://<storage-account>.blob.core.windows.net/<container>'
    CREDENTIALS = (AZURE_SAS_TOKEN = '<sas-token>');
